image: mcr.microsoft.com/dotnet/sdk:5.0

variables:
    PACKAGE_VERSION: "$CI_JOB_ID$MONTH_YEAR"

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - dotnet build -c $CONFIGURATION
    artifacts:
      paths:
        - src/
    only:
        - merge_requests
        - master

test:
    stage: test
    script:
        - dotnet test -c $CONFIGURATION
    only:
        - merge_requests
        - master

deploy:
    stage: deploy
    script:
        - echo $PACKAGE_VERSION
        - dotnet pack ./src/General.Extensions/General.Extensions.csproj -p:PackageVersion=$PACKAGE_VERSION -o:Packages --no-restore
    artifacts:
        paths:
        - Packages/
    only:
        - master