image: mcr.microsoft.com/dotnet/sdk:5.0

variables:
    PACKAGE_VERSION: "$MONTH_YEAR$CI_JOB_ID"

stages:
    - build
    - test
    - pack
    - publish

build:
    stage: build
    script:
        - dotnet build -c $CONFIGURATION
    artifacts:
      paths:
        - src/
        - test/
    only:
        - merge_requests
        - master

test:
    stage: test
    script:
        - dotnet vstest test/General.Extensions.UnitTests/bin/Release/net5.0/General.Extensions.UnitTests.dll
    only:
        - merge_requests
        - master

pack:
    stage: pack
    script:
        - dotnet pack ./src/General.Extensions/General.Extensions.csproj -p:PackageVersion="$PACKAGE_VERSION" -o:Packages --no-restore
    artifacts:
        paths:
        - Packages/
    only:
        - master

publish:
    stage: publish
    script:
        - dotnet nuget push Packages/General.Extensions.$PACKAGE_VERSION.nupkg -k $NUGET_API_KEY -s $NUGET_FEED
    only:
        - master