image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - build
    - test
    - deploy

before_script:
    - echo "running Before scripts"
    - dotnet --version

build:
    stage: build
    script:
        - echo "run dotnet build -c:Release"
        - "dotnet build -c:Release"
    artifacts:
      paths:
        - bin/

test:
    stage: test
    script: 
        - echo "run test -c:Release"
        - "dotnet test -c:Release"
    coverage: /\|\s*Total\s*\|\s*(\d+[,.]\d+%)/

deploy:
    stage: deploy
    script:
        - echo "run dotnet deploy"
        - "dotnet --version"