image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - dotnet build -c Release
    artifacts:
      paths:
        - src/

test:
    stage: test
    script:
        - dotnet test -c Release

deploy:
    stage: deploy
    script:
        - dotnet pack ./src/General.Extensions/General.Extensions.csproj -p:PackageVersion=$CI_JOB_ID -o:Packages --no-restore
    artifacts:
        paths:
        - Packages/