image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - build
    - test
    - deploy

before_script:
    - dotnet --version
    - nuget help | select-string Version

build:
    only:
        - merge_request
    stage: build
    script:
        - "dotnet build -c:Release"
    artifacts:
      paths:
        - bin/

test:
    stage: test
    script: 
        - "dotnet test -c:Release"
    coverage: /\|\s*Total\s*\|\s*(\d+[,.]\d+%)/

deploy:
    only:
        - merge_request
        - master
    stage: deploy
    script:
        - "dotnet --version"
