image: mcr.microsoft.com/dotnet/sdk:5.0

variables:
    MAIN_VERSION: 2
    
before_script:
     - YEAR=$(date +"%y")
     - MONTH=$(date +"%m" | sed 's/0//')
     - MINOR_VERSION=$CI_PIPELINE_IID
     - PACKAGE_VERSION=${MAIN_VERSION}.${YEAR}.${MONTH}.${MINOR_VERSION}

stages:
    - build
    - unit_tests
    - pack
    - publish

build:
    stage: build
    script:
        - dotnet build -c $CONFIGURATION
    artifacts:
      paths:
        - src/
        - test/
    only:
        - merge_requests
        - master

unit_tests:
    stage: unit_tests
    script:
        - dotnet test test/General.Extensions.UnitTests/General.Extensions.UnitTests.csproj -c $CONFIGURATION --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
    artifacts:
        when: always
        paths:
            - ./**/*test-result.xml
        reports:
            junit:
            - ./**/*test-result.xml
    only:
        - merge_requests
        - master

pack:
    stage: pack
    script:
        - dotnet pack src/General.Extensions/General.Extensions.csproj -p:PackageVersion="$PACKAGE_VERSION" -o:packages --no-restore
    artifacts:
        paths:
        - packages/
    only:
        - master

publish:
    stage: publish
    script:
        - dotnet nuget push packages/General.Extensions.$PACKAGE_VERSION.nupkg -k $NUGET_API_KEY -s $NUGET_FEED
    only:
        - master