image: mcr.microsoft.com/dotnet/sdk:5.0

before_script:
    - dotnet --version

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - dotnet build -c Release
    artifacts:
      paths:
        - src/

test:
    stage: test
    script:
        - dotnet test -c Release /p:CollectCoverage=true
    coverage: /\|\s*Total\s*\|\s*(\d+[,.]\d+%)/

deploy:
    stage: deploy
    script:
        - dotnet --version