name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test test/General.Extensions.UnitTests/General.Extensions.UnitTests.csproj --no-build --verbosity normal -c Release
    - name: Collect_Test_Results
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: |
          src
          test
        retention-days: 2
